name: Push Files to Org docs Repository

on:
  push:
    branches:
      - main

jobs:
  push_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Copy Files to Another Repository
        run: |
          git clone https://github.com/Ali-Ozturk/docs-prot-org-1.git
          cp ./src/README.md docs-prot-org-1/docs/
          cd docs-prot-org-1
          git add .
          git commit -m "Update files"
          git push