on:
  push:
    branches:
      - main

jobs:
  push_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git config --global credential.helper store

      - name: Copy Files to Another Repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://github.com/Ali-Ozturk/docs-prot-org-1.git
          cp ./src/README.md docs-prot-org-1/docs/
          cd docs-prot-org-1
          git add .
          git commit -m "Update files"
          git config --local user.email "your-email@example.com"
          git config --local user.name "Your Name"
          git remote set-url origin "https://$PAT@github.com/Ali-Ozturk/docs-prot-org-1.git"
          git push origin HEAD:main